import fs from 'node:fs';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

import {
  LOGO_MARK_FILES,
  LOGO_MARK_SIZE,
  MOTION_ASSET_SPECS,
  MOTION_DIMS,
  parseGif,
  parsePngSize,
} from './motion-spec';

// Committed production assets (regenerated by scripts/email-motion/generate.mjs).
const MOTION_DIR = path.resolve(__dirname, '../../../public/email/motion');
const EMAIL_DIR = path.resolve(__dirname, '../../../public/email');

describe('email motion assets', () => {
  describe.each(MOTION_ASSET_SPECS)('$file', (spec) => {
    const file = path.join(MOTION_DIR, spec.file);

    it('exists', () => {
      expect(fs.existsSync(file), `${spec.file} missing — run node scripts/email-motion/generate.mjs`).toBe(true);
    });

    it(`is exactly ${MOTION_DIMS.width}x${MOTION_DIMS.height}`, () => {
      const info = parseGif(fs.readFileSync(file));
      expect({ width: info.width, height: info.height }).toEqual(MOTION_DIMS);
    });

    it(`is under its ${spec.maxKB} KB MOTION cap`, () => {
      expect(fs.statSync(file).size).toBeLessThanOrEqual(spec.maxKB * 1024);
    });

    it(`carries Netscape loop ${spec.loop}`, () => {
      expect(parseGif(fs.readFileSync(file)).loopCount).toBe(spec.loop);
    });

    it('is animated (frame count > 1)', () => {
      expect(parseGif(fs.readFileSync(file)).frameCount).toBeGreaterThan(1);
    });
  });

  describe.each(LOGO_MARK_FILES.map((f) => ({ file: f })))('$file', ({ file }) => {
    it(`exists and is ${LOGO_MARK_SIZE}x${LOGO_MARK_SIZE} (22x22 display @2x)`, () => {
      const p = path.join(EMAIL_DIR, file);
      expect(fs.existsSync(p), `${file} missing — run node scripts/email-motion/generate.mjs`).toBe(true);
      expect(parsePngSize(fs.readFileSync(p))).toEqual({ width: LOGO_MARK_SIZE, height: LOGO_MARK_SIZE });
    });
  });
});
