import { Document, Image, Page, Text, View } from '@react-pdf/renderer';

import {
  PDF_COLORS,
  formatDateForPdf,
  formatNumberForPdf,
  pdfStyles,
} from './styles';

// ── Local palette ──────────────────────────────────────────────────
// Editorial warm-copper accent — used on STATUS chips and any
// non-zero B/O quantity so the receiver's eye lands on the
// back-ordered lines without having to scan every row.
const ACCENT = '#a8632e';
const CARD_BORDER = PDF_COLORS.line;
const CARD_RADIUS = 4;

export interface ShipmentPdfLine {
  /** ISBN if barcode set, else SKU. */
  isbn: string;
  description: string;
  /** Optional second-line subtitle under description — typically an
   * author for book lines, pulled from inventory_items.custom_fields.author
   * by the route. Falls back to nothing when empty. */
  subtitle?: string | null;
  qtyShipped: number;
  qtyBackOrdered: number;
}

export interface ShipmentPdfWarehouse {
  name: string;
  /** Address as a denormalized list of lines (line1, line2, "City, State Zip"). */
  addressLines: string[];
  contactPhone: string | null;
  contactEmail: string | null;
}

/**
 * Destination is a CHARTER (the receiving site/school), not a warehouse.
 * Charters have no address field in the schema, so the destination block
 * shows only name + code + attention. That matches the L4L word-template
 * style: "Ship To: CVW-MANCHESTER" is a charter code, not an address.
 */
export interface ShipmentPdfCharter {
  name: string;
  code: string | null;
}

export interface ShipmentPdfManagerBlock {
  fullName: string | null;
  role: string | null;
  warehouseAddressLines: string[];
  phone: string | null;
  email: string | null;
}

export interface ShipmentPdfHeader {
  workOrderNumber: string;
  shipDate: string;
  attentionToName: string | null;
  notes: string | null;
  /** 'delivered' suppresses the QR-to-sign block (no point — already signed). */
  status: 'draft' | 'shipped' | 'delivered' | 'cancelled';
}

export interface ShipmentPdfOrg {
  name: string;
  logoUrl: string | null;
}

export interface ShipmentPdfSignature {
  /** PNG data URL (or http URL); displayed inside a 200x60pt contain-box. */
  imageDataUrl: string;
  signedByName: string | null;
  signedAt: string | Date;
}

interface ShipmentPdfProps {
  org: ShipmentPdfOrg;
  shipment: ShipmentPdfHeader;
  source: ShipmentPdfWarehouse;
  /** Receiving charter — name + code, no address. */
  destination: ShipmentPdfCharter;
  lines: ShipmentPdfLine[];
  manager: ShipmentPdfManagerBlock | null;
  /**
   * Data URL of a QR code that points to the public signature page. Rendered
   * in the bottom card alongside the manager contact when the shipment is
   * still awaiting signature. Generated by the caller — use the `qrcode`
   * package's `toDataURL`.
   */
  qrDataUrl?: string | null;
  /**
   * Signature image + caption. When non-null we render the captured signature
   * inside the receipt strip instead of the blank pen-stroke line.
   */
  signature?: ShipmentPdfSignature | null;
}

// ── Helpers ────────────────────────────────────────────────────────

/**
 * Helper that flattens a Postgres jsonb address into the kind of
 * denormalized line list a packing slip wants. Missing pieces become
 * empty lines so we never render literal "null".
 */
export function addressJsonToLines(
  address: Record<string, unknown> | null,
): string[] {
  if (!address) return [];
  const line1 = (address.line1 as string | null) ?? '';
  const line2 = (address.line2 as string | null) ?? '';
  const city = (address.city as string | null) ?? '';
  const region = (address.region as string | null) ?? '';
  const postal = (address.postalCode as string | null) ?? '';
  const country = (address.country as string | null) ?? '';
  const cityLine = [city, region].filter(Boolean).join(', ');
  const cityZip = [cityLine, postal].filter(Boolean).join(' ').trim();
  return [line1, line2, cityZip, country].filter((s) => s.trim().length > 0);
}

/**
 * Extract a "short" WO display from an ISR-style work order number.
 *   "ISR-CVW-MANCHESTER-04292026"  →  "WO-04292026"
 * For non-ISR formats just prefix with WO-.
 */
function shortWorkOrder(wo: string): string {
  const parts = wo.split('-');
  const last = parts[parts.length - 1] ?? wo;
  return /^\d{6,}$/.test(last) ? `WO-${last}` : `WO-${wo}`;
}

function statusLabels(status: ShipmentPdfHeader['status']): {
  primary: string;
  secondary: string;
  emphasize: boolean;
} {
  switch (status) {
    case 'draft':
      return { primary: 'Ready', secondary: 'Awaiting carrier', emphasize: true };
    case 'shipped':
      return { primary: 'Shipped', secondary: 'In transit', emphasize: true };
    case 'delivered':
      return { primary: 'Delivered', secondary: 'Signed by receiver', emphasize: false };
    case 'cancelled':
      return { primary: 'Cancelled', secondary: 'Voided', emphasize: false };
    default:
      return { primary: '—', secondary: '', emphasize: false };
  }
}

// ── Component ──────────────────────────────────────────────────────

export function ShipmentPdf({
  org,
  shipment,
  source,
  destination,
  lines,
  manager,
  qrDataUrl,
  signature,
}: ShipmentPdfProps) {
  const totalShipped = lines.reduce((s, l) => s + (Number(l.qtyShipped) || 0), 0);
  const totalBo = lines.reduce((s, l) => s + (Number(l.qtyBackOrdered) || 0), 0);
  const status = statusLabels(shipment.status);
  const showQr = !!qrDataUrl && shipment.status !== 'delivered' && shipment.status !== 'cancelled';

  // Renders the inline timestamp on the right of the masthead, e.g.
  // "Apr 29 2026 · 09:14 PT". Locale TZ short name from the runtime.
  const now = new Date();
  const dateLong = now.toLocaleDateString('en-US', {
    month: 'short',
    day: '2-digit',
    year: 'numeric',
  });
  const time = now
    .toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: false,
      timeZoneName: 'short',
    })
    .replace(',', '');

  const wide = { letterSpacing: 1.4 };

  return (
    <Document title={`Packing slip ${shipment.workOrderNumber}`}>
      <Page size="LETTER" style={pdfStyles.page}>
        {/* ── MASTHEAD ─────────────────────────────────────────────
            Org logo + name on the left, slim divider, "PACKING SLIP ·
            INVENTORY TRANSFER" as the document kicker, generation
            timestamp on the right. */}
        <View
          style={{
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingBottom: 10,
            borderBottomWidth: 1,
            borderBottomColor: PDF_COLORS.ink,
            borderBottomStyle: 'solid',
          }}
        >
          <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}>
            {org.logoUrl ? (
              // eslint-disable-next-line jsx-a11y/alt-text
              <Image src={org.logoUrl} style={{ width: 22, height: 22, objectFit: 'contain' }} />
            ) : null}
            <Text style={{ fontFamily: 'Helvetica-Bold', fontSize: 13 }}>{org.name}</Text>
            <Text style={{ color: PDF_COLORS.ink4, fontSize: 9 }}>|</Text>
            <Text
              style={[
                wide,
                { fontSize: 9, color: PDF_COLORS.ink3, textTransform: 'uppercase' },
              ]}
            >
              Packing Slip · Inventory Transfer
            </Text>
          </View>
          <Text style={{ fontSize: 8.5, color: PDF_COLORS.ink3 }}>
            {dateLong} · {time}
          </Text>
        </View>

        {/* ── 4-CARD META ROW ──────────────────────────────────────
            Work order / Ship date / Page / Status. Status uses the
            warm-copper accent when emphasized (Ready, Shipped). */}
        <View style={{ flexDirection: 'row', gap: 10, marginTop: 16 }}>
          {[
            {
              label: 'Work Order',
              big: shortWorkOrder(shipment.workOrderNumber),
              sub: shipment.workOrderNumber,
              subMono: true,
              accent: false,
            },
            {
              label: 'Ship Date',
              big: formatShipDateBig(shipment.shipDate),
              sub: formatDateForPdf(shipment.shipDate),
              subMono: false,
              accent: false,
            },
            {
              label: 'Page',
              big: '1/1',
              sub: 'Single page',
              subMono: false,
              accent: false,
            },
            {
              label: 'Status',
              big: status.primary,
              sub: status.secondary,
              subMono: false,
              accent: status.emphasize,
            },
          ].map((c) => (
            <View
              key={c.label}
              style={{
                flex: 1,
                minWidth: 0,
                borderWidth: 0.7,
                borderColor: CARD_BORDER,
                borderStyle: 'solid',
                borderRadius: CARD_RADIUS,
                padding: 10,
                overflow: 'hidden',
              }}
            >
              <Text
                style={[
                  wide,
                  {
                    fontSize: 7.5,
                    color: PDF_COLORS.ink3,
                    textTransform: 'uppercase',
                    marginBottom: 4,
                  },
                ]}
              >
                {c.label}
              </Text>
              <Text
                style={{
                  fontFamily: 'Helvetica-Bold',
                  fontSize: 14,
                  color: c.accent ? ACCENT : PDF_COLORS.ink,
                }}
              >
                {c.big}
              </Text>
              {/* Subtitle: WO# can be 24-30 chars in mono (ISR-{CODE}-MMDDYYYY)
                  which overflows ~105pt of usable card width at 8pt Courier
                  for the longer charter codes. Drop to 6.5pt mono and 7.5pt
                  proportional so the longest realistic codes fit on one line. */}
              <Text
                style={{
                  fontSize: c.subMono ? 6.5 : 7.5,
                  color: PDF_COLORS.ink3,
                  marginTop: 3,
                  fontFamily: c.subMono ? 'Courier' : 'Helvetica',
                }}
              >
                {c.sub}
              </Text>
            </View>
          ))}
        </View>

        {/* ── FROM / SHIP TO ROW ───────────────────────────────────
            Two cards with a chevron between them so it reads as a
            transfer direction at a glance. */}
        <View
          style={{
            flexDirection: 'row',
            alignItems: 'stretch',
            gap: 10,
            marginTop: 14,
          }}
        >
          <View
            style={{
              flex: 1,
              borderWidth: 0.7,
              borderColor: CARD_BORDER,
              borderStyle: 'solid',
              borderRadius: CARD_RADIUS,
              padding: 12,
            }}
          >
            <Text
              style={[
                wide,
                {
                  fontSize: 7.5,
                  color: PDF_COLORS.ink3,
                  textTransform: 'uppercase',
                  marginBottom: 6,
                },
              ]}
            >
              From
            </Text>
            <Text style={{ fontFamily: 'Helvetica-Bold', fontSize: 12 }}>
              {source.name}
            </Text>
            {source.addressLines.map((l, i) => (
              // eslint-disable-next-line react/no-array-index-key
              <Text key={`from-${i}`} style={{ fontSize: 8.5, color: PDF_COLORS.ink3, marginTop: 2 }}>
                {l}
              </Text>
            ))}
          </View>

          <View style={{ alignItems: 'center', justifyContent: 'center' }}>
            <Text style={{ fontSize: 16, color: PDF_COLORS.ink4 }}>›</Text>
          </View>

          <View
            style={{
              flex: 1,
              borderWidth: 0.7,
              borderColor: CARD_BORDER,
              borderStyle: 'solid',
              borderRadius: CARD_RADIUS,
              padding: 12,
            }}
          >
            <Text
              style={[
                wide,
                {
                  fontSize: 7.5,
                  color: PDF_COLORS.ink3,
                  textTransform: 'uppercase',
                  marginBottom: 6,
                },
              ]}
            >
              Ship To
            </Text>
            {/* Headline with the readable charter name (matches the new
                design mockup — "CVW — Manchester"), then a mono line
                with the slugified code beneath. Code is also embedded
                in the WO# above and visible under the QR, but having
                it on the Ship To card too means a picker scanning the
                slip doesn't have to read the WO# to know which charter
                they're packing for. */}
            <Text style={{ fontFamily: 'Helvetica-Bold', fontSize: 12 }}>
              {destination.name || destination.code || '—'}
            </Text>
            {destination.code ? (
              <Text
                style={{
                  fontFamily: 'Courier',
                  fontSize: 8.5,
                  color: PDF_COLORS.ink3,
                  marginTop: 2,
                }}
              >
                {destination.code}
              </Text>
            ) : null}
            {/* Hairline separator before the attention line — mirrors the
                "underlined headline" look in the design mockup. */}
            <View
              style={{
                marginTop: 6,
                marginBottom: 6,
                borderBottomWidth: 0.5,
                borderBottomColor: CARD_BORDER,
                borderBottomStyle: 'solid',
              }}
            />
            <Text style={{ fontSize: 9, color: PDF_COLORS.ink3 }}>
              Attention · {shipment.attentionToName ?? '—'}
            </Text>
          </View>
        </View>

        {/* ── NOTES (optional) ─────────────────────────────────── */}
        {shipment.notes ? (
          <View style={{ marginTop: 14 }}>
            <Text
              style={[
                wide,
                {
                  fontSize: 7.5,
                  color: PDF_COLORS.ink3,
                  textTransform: 'uppercase',
                  marginBottom: 4,
                },
              ]}
            >
              Notes
            </Text>
            <Text style={{ fontSize: 9, color: PDF_COLORS.ink2 }}>{shipment.notes}</Text>
          </View>
        ) : null}

        {/* ── ITEMS TABLE ──────────────────────────────────────── */}
        <View style={{ marginTop: 18 }}>
          <View
            style={{
              flexDirection: 'row',
              paddingVertical: 6,
              paddingHorizontal: 4,
              borderBottomWidth: 0.7,
              borderBottomColor: PDF_COLORS.ink2,
              borderBottomStyle: 'solid',
            }}
            fixed
          >
            <Text style={[wide, headColStyle, { flex: 5 }]}>#</Text>
            <Text style={[wide, headColStyle, { flex: 50 }]}>Description</Text>
            <Text style={[wide, headColStyle, { flex: 22 }]}>ISBN</Text>
            <Text style={[wide, headColStyle, { flex: 13, textAlign: 'right' }]}>Qty Ship</Text>
            <Text style={[wide, headColStyle, { flex: 10, textAlign: 'right' }]}>B/O</Text>
          </View>

          {lines.length === 0 ? (
            <View style={{ paddingVertical: 12 }}>
              <Text style={{ color: PDF_COLORS.ink3, fontSize: 9, textAlign: 'center' }}>
                No line items.
              </Text>
            </View>
          ) : (
            lines.map((l, i) => {
              const idx = String(i + 1).padStart(2, '0');
              const boZero = !l.qtyBackOrdered;
              return (
                <View
                  // eslint-disable-next-line react/no-array-index-key
                  key={`${l.isbn}-${i}`}
                  wrap={false}
                  style={{
                    flexDirection: 'row',
                    alignItems: 'center',
                    paddingVertical: 8,
                    paddingHorizontal: 4,
                    borderBottomWidth: 0.5,
                    borderBottomColor: PDF_COLORS.line,
                    borderBottomStyle: 'solid',
                  }}
                >
                  <Text style={{ flex: 5, fontFamily: 'Courier', fontSize: 8.5, color: PDF_COLORS.ink3 }}>
                    {idx}
                  </Text>
                  <View style={{ flex: 50, paddingRight: 6 }}>
                    <Text style={{ fontFamily: 'Helvetica-Bold', fontSize: 9.5 }}>
                      {l.description}
                    </Text>
                    {l.subtitle ? (
                      <Text style={{ fontSize: 8.5, color: PDF_COLORS.ink3, marginTop: 1 }}>
                        {l.subtitle}
                      </Text>
                    ) : null}
                  </View>
                  <Text
                    style={{
                      flex: 22,
                      fontFamily: 'Courier',
                      fontSize: 9,
                      color: PDF_COLORS.ink2,
                    }}
                  >
                    {l.isbn || '—'}
                  </Text>
                  <Text
                    style={{
                      flex: 13,
                      textAlign: 'right',
                      fontFamily: 'Helvetica-Bold',
                      fontSize: 10,
                    }}
                  >
                    {formatNumberForPdf(l.qtyShipped)}
                  </Text>
                  <Text
                    style={{
                      flex: 10,
                      textAlign: 'right',
                      fontFamily: boZero ? 'Helvetica' : 'Helvetica-Bold',
                      fontSize: 10,
                      color: boZero ? PDF_COLORS.ink3 : ACCENT,
                    }}
                  >
                    {formatNumberForPdf(l.qtyBackOrdered)}
                  </Text>
                </View>
              );
            })
          )}

          {/* Total row */}
          <View
            wrap={false}
            style={{
              flexDirection: 'row',
              alignItems: 'center',
              paddingVertical: 10,
              paddingHorizontal: 4,
            }}
          >
            <Text style={{ flex: 5 }} />
            <Text
              style={[
                wide,
                {
                  flex: 50,
                  fontSize: 8,
                  color: PDF_COLORS.ink3,
                  textTransform: 'uppercase',
                },
              ]}
            >
              Total · {lines.length} {lines.length === 1 ? 'Line' : 'Lines'}
            </Text>
            <Text style={{ flex: 22 }} />
            <Text
              style={{
                flex: 13,
                textAlign: 'right',
                fontFamily: 'Helvetica-Bold',
                fontSize: 12,
              }}
            >
              {formatNumberForPdf(totalShipped)}
            </Text>
            <Text
              style={{
                flex: 10,
                textAlign: 'right',
                fontFamily: 'Helvetica-Bold',
                fontSize: 12,
                color: totalBo ? ACCENT : PDF_COLORS.ink3,
              }}
            >
              {formatNumberForPdf(totalBo)}
            </Text>
          </View>
        </View>

        {/* ── QR + CONTACT CARD ────────────────────────────────────
            Replaces the linear barcode in the original L4L slip. QR
            payload is the public /s/{token} signature page. When the
            shipment is already delivered or cancelled we drop the QR
            and show the contact info full-width. */}
        <View
          wrap={false}
          style={{
            marginTop: 16,
            flexDirection: 'row',
            alignItems: 'center',
            borderWidth: 0.7,
            borderColor: CARD_BORDER,
            borderStyle: 'solid',
            borderRadius: CARD_RADIUS,
            padding: 12,
          }}
        >
          {showQr ? (
            <View style={{ alignItems: 'center', marginRight: 18 }}>
              {/* eslint-disable-next-line jsx-a11y/alt-text */}
              <Image src={qrDataUrl as string} style={{ width: 78, height: 78 }} />
              <Text
                style={{
                  fontFamily: 'Courier',
                  fontSize: 7,
                  color: PDF_COLORS.ink3,
                  marginTop: 4,
                  letterSpacing: 0.5,
                }}
              >
                {shipment.workOrderNumber}
              </Text>
              <Text
                style={[
                  wide,
                  {
                    fontSize: 6.5,
                    color: PDF_COLORS.ink4,
                    textTransform: 'uppercase',
                    marginTop: 2,
                  },
                ]}
              >
                Scan to sign
              </Text>
            </View>
          ) : null}

          <View style={{ flex: 1 }}>
            <Text
              style={[
                wide,
                {
                  fontSize: 7.5,
                  color: PDF_COLORS.ink3,
                  textTransform: 'uppercase',
                  marginBottom: 4,
                },
              ]}
            >
              Contact
            </Text>
            {manager?.fullName ? (
              <Text style={{ fontFamily: 'Helvetica-Bold', fontSize: 10 }}>
                {manager.fullName}
              </Text>
            ) : null}
            {manager?.role ? (
              <Text style={{ fontSize: 9, color: PDF_COLORS.ink3 }}>{manager.role}</Text>
            ) : null}
          </View>
          <View style={{ alignItems: 'flex-end' }}>
            {manager?.phone ? (
              <Text style={{ fontSize: 9.5, fontFamily: 'Helvetica-Bold' }}>
                {manager.phone}
              </Text>
            ) : null}
            {manager?.email ? (
              <Text style={{ fontSize: 9, color: PDF_COLORS.ink3, marginTop: 2 }}>
                {manager.email}
              </Text>
            ) : null}
          </View>
        </View>

        {/* ── SIGNATURE ROW ────────────────────────────────────────
            PRINT NAME · SIGNATURE · DATE RECEIVED. When we've captured
            an electronic signature we render it inline above the
            SIGNATURE label instead of leaving the line blank. */}
        <View
          wrap={false}
          style={{
            marginTop: 28,
            flexDirection: 'row',
            gap: 18,
            paddingTop: 14,
            borderTopWidth: 0.5,
            borderTopColor: CARD_BORDER,
            borderTopStyle: 'solid',
          }}
        >
          {[
            { label: 'Print Name', content: null as React.ReactNode },
            {
              label: 'Signature',
              content: signature ? (
                // eslint-disable-next-line jsx-a11y/alt-text
                <Image
                  src={signature.imageDataUrl}
                  style={{ width: '100%', height: 26, objectFit: 'contain' }}
                />
              ) : null,
            },
            {
              label: 'Date Received',
              content: signature ? (
                <Text style={{ fontSize: 9 }}>
                  {formatDateForPdf(
                    typeof signature.signedAt === 'string'
                      ? signature.signedAt
                      : signature.signedAt.toISOString(),
                  )}
                </Text>
              ) : null,
            },
          ].map((c, i) => (
            <View key={c.label} style={{ flex: 1 }}>
              <View style={{ minHeight: 26, justifyContent: 'flex-end', marginBottom: 4 }}>
                {c.content}
              </View>
              <View
                style={{
                  borderBottomWidth: 0.7,
                  borderBottomColor: PDF_COLORS.ink2,
                  borderBottomStyle: 'solid',
                  marginBottom: 4,
                }}
              />
              <Text
                style={[
                  wide,
                  {
                    fontSize: 7.5,
                    color: PDF_COLORS.ink3,
                    textTransform: 'uppercase',
                  },
                ]}
                // hint for unused-warning in some configs
                {...(i < 0 ? { hidden: true } : {})}
              >
                {c.label}
              </Text>
            </View>
          ))}
        </View>

        {signature?.signedByName ? (
          <Text
            style={{
              marginTop: 6,
              fontSize: 8,
              color: PDF_COLORS.ink3,
              textAlign: 'center',
            }}
          >
            Signed by {signature.signedByName}
          </Text>
        ) : null}

        {/* ── PAGE FOOTER ──────────────────────────────────────── */}
        <View
          fixed
          style={{
            position: 'absolute',
            bottom: 24,
            left: 40,
            right: 40,
            flexDirection: 'row',
            justifyContent: 'space-between',
            paddingTop: 6,
            borderTopWidth: 0.5,
            borderTopColor: PDF_COLORS.line,
            borderTopStyle: 'solid',
          }}
        >
          <Text
            style={[
              wide,
              {
                fontSize: 7.5,
                color: PDF_COLORS.ink4,
                textTransform: 'uppercase',
              },
            ]}
          >
            {org.name} · stockpilot.app
          </Text>
          <Text
            style={[
              wide,
              {
                fontSize: 7.5,
                color: PDF_COLORS.ink4,
                textTransform: 'uppercase',
              },
            ]}
            render={({ pageNumber, totalPages }) =>
              `${shortWorkOrder(shipment.workOrderNumber)} · ${pageNumber}/${totalPages}`
            }
          />
        </View>
      </Page>
    </Document>
  );
}

const headColStyle = {
  fontSize: 7.5,
  fontFamily: 'Helvetica-Bold' as const,
  color: PDF_COLORS.ink3,
  textTransform: 'uppercase' as const,
};

function formatShipDateBig(iso: string | Date | null | undefined): string {
  if (!iso) return '—';
  const d = typeof iso === 'string' ? new Date(iso) : iso;
  if (Number.isNaN(d.getTime())) return '—';
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  const yyyy = String(d.getFullYear());
  return `${mm}/${dd}/${yyyy}`;
}
