import { beforeEach, describe, expect, it, vi } from 'vitest';

/**
 * The two AI draft tools report what the buttons report (S3 F1 / D5):
 *   - draftPosFromForecast skips items already on an open PO and says how
 *     many, so the model does not claim "nothing below par" when there was;
 *   - draftPos drafts the chosen items as asked but says how many were
 *     already on another open PO, or that it could not check.
 */

const { listMock, createDraftsFromItems, autoGenerateDraftPOs } = vi.hoisted(() => ({
  listMock: vi.fn(),
  createDraftsFromItems: vi.fn(),
  autoGenerateDraftPOs: vi.fn(),
}));

vi.mock('@/lib/error-reporter', () => ({ reportError: vi.fn(async () => {}) }));
vi.mock('@/server/services/inventory', () => ({
  InventoryService: class {
    list(...args: unknown[]) {
      return listMock(...args);
    }
  },
}));
vi.mock('@/server/services/purchase-orders', () => ({
  PurchaseOrdersService: class {
    createDraftsFromItems(...args: unknown[]) {
      return createDraftsFromItems(...args);
    }
  },
}));
vi.mock('@/server/services/planning', () => ({
  PlanningService: class {
    autoGenerateDraftPOs(...args: unknown[]) {
      return autoGenerateDraftPOs(...args);
    }
  },
}));
vi.mock('@/server/services/movements', () => ({
  MovementsService: class {},
  getDashboardActions: vi.fn(),
  getDashboardSummary: vi.fn(),
  getLowStockItems: vi.fn(),
}));
vi.mock('@/server/services/categories', () => ({ CategoriesService: class {} }));
vi.mock('@/server/services/suppliers', () => ({ SuppliersService: class {} }));
vi.mock('@/server/services/warehouses', () => ({ WarehousesService: class {} }));
vi.mock('@/server/services/order-requests', () => ({ OrderRequestsService: class {} }));
vi.mock('@/server/services/bundles', () => ({ BundlesService: class {} }));
vi.mock('@/server/services/books-import', () => ({ BooksImportService: class {} }));
vi.mock('@/server/services/forecasting', () => ({
  getItemVelocity: vi.fn(),
  suggestReorderPoint: vi.fn(),
}));
vi.mock('@/lib/books/lookup', () => ({ lookupIsbn: vi.fn() }));

import { makeServiceContext, makeSupabaseStub } from '@/test/supabase-mock';

import { draftPosFromForecastSummary, draftPosSummary, TOOL_CATALOG } from './tools';

const ctx = () => makeServiceContext(makeSupabaseStub({}).client) as never;

beforeEach(() => {
  vi.clearAllMocks();
});

describe('draftPosFromForecast', () => {
  it('passes skippedOnOpenPo through and says every below-par item is already on order', async () => {
    autoGenerateDraftPOs.mockResolvedValue({
      createdPoIds: [],
      unassignedCount: 0,
      skipped: 0,
      skippedOnOpenPo: 3,
      supplierFailures: [],
      supplierCount: 0,
    });
    const out = (await TOOL_CATALOG.draftPosFromForecast!.execute({}, ctx())) as {
      skippedOnOpenPo: number;
      summary: string;
    };
    expect(autoGenerateDraftPOs).toHaveBeenCalledWith();
    expect(out.skippedOnOpenPo).toBe(3);
    expect(out.summary).toBe(
      'No drafts created: all 3 below-par items are already on open purchase orders.',
    );
  });

  it('names the skipped count next to the drafts it did create', () => {
    expect(
      draftPosFromForecastSummary({
        createdPoIds: ['a', 'b'],
        unassignedCount: 1,
        skippedOnOpenPo: 1,
        supplierFailures: [],
      }),
    ).toBe(
      'Created 2 draft POs. 1 item on an unassigned draft (set a supplier). 1 below-par item was skipped because already on an open purchase order.',
    );
  });

  it('keeps "nothing below par" for the genuinely empty case', () => {
    expect(
      draftPosFromForecastSummary({
        createdPoIds: [],
        unassignedCount: 0,
        skippedOnOpenPo: 0,
        supplierFailures: [],
      }),
    ).toBe('No drafts created: nothing is below its reorder point.');
  });
});

describe('draftPos', () => {
  it('drafts the matched items and reports how many were already on an open PO', async () => {
    listMock.mockResolvedValue({ total: 2, items: [{ id: 'i-1' }, { id: 'i-2' }] });
    createDraftsFromItems.mockResolvedValue({
      createdPoIds: ['po-1'],
      skipped: 0,
      alreadyOnOpenPo: 2,
      supplierFailures: [],
      supplierCount: 1,
    });
    const out = (await TOOL_CATALOG.draftPos!.execute({}, ctx())) as {
      alreadyOnOpenPo: number | null;
      summary: string;
    };
    // The whole selection goes to the service: nothing is dropped for being on order.
    expect(createDraftsFromItems).toHaveBeenCalledWith(['i-1', 'i-2']);
    expect(out.alreadyOnOpenPo).toBe(2);
    expect(out.summary).toBe(
      'Created 1 draft PO. 2 of the drafted items were already on another open purchase order; review the drafts before sending.',
    );
  });

  it('says it could not check instead of implying none were on order', () => {
    expect(
      draftPosSummary({ createdPoIds: ['po-1'], skipped: 1, alreadyOnOpenPo: null, supplierFailures: [] }),
    ).toBe(
      'Created 1 draft PO. 1 item skipped (no supplier). Could not check whether any of these items are already on open purchase orders.',
    );
  });
});
