import { beforeEach, describe, expect, it, vi } from 'vitest';

/**
 * The two AI draft tools report what the buttons report (S3 F1 / D5):
 *   - draftPosFromForecast skips items already on an open PO and says how
 *     many, so the model does not claim "nothing below par" when there was;
 *   - draftPos drafts the chosen items as asked but says how many were
 *     already on another open PO, or that it could not check.
 */

const {
  listMock,
  getMock,
  updateMock,
  createDraftsFromItems,
  autoGenerateDraftPOs,
  getReorderSuggestions,
} = vi.hoisted(() => ({
  listMock: vi.fn(),
  getMock: vi.fn(),
  updateMock: vi.fn(),
  createDraftsFromItems: vi.fn(),
  autoGenerateDraftPOs: vi.fn(),
  getReorderSuggestions: vi.fn(),
}));

vi.mock('@/lib/error-reporter', () => ({ reportError: vi.fn(async () => {}) }));
vi.mock('@/server/services/inventory', () => ({
  InventoryService: class {
    list(...args: unknown[]) {
      return listMock(...args);
    }
    get(...args: unknown[]) {
      return getMock(...args);
    }
    update(...args: unknown[]) {
      return updateMock(...args);
    }
  },
}));
vi.mock('@/server/services/purchase-orders', () => ({
  PurchaseOrdersService: class {
    createDraftsFromItems(...args: unknown[]) {
      return createDraftsFromItems(...args);
    }
  },
}));
vi.mock('@/server/services/planning', () => ({
  PlanningService: class {
    autoGenerateDraftPOs(...args: unknown[]) {
      return autoGenerateDraftPOs(...args);
    }
    getReorderSuggestions(...args: unknown[]) {
      return getReorderSuggestions(...args);
    }
  },
}));
vi.mock('@/server/services/movements', () => ({
  MovementsService: class {},
  getDashboardActions: vi.fn(),
  getDashboardSummary: vi.fn(),
  getLowStockItems: vi.fn(),
}));
vi.mock('@/server/services/categories', () => ({ CategoriesService: class {} }));
vi.mock('@/server/services/suppliers', () => ({ SuppliersService: class {} }));
vi.mock('@/server/services/warehouses', () => ({ WarehousesService: class {} }));
vi.mock('@/server/services/order-requests', () => ({ OrderRequestsService: class {} }));
vi.mock('@/server/services/bundles', () => ({ BundlesService: class {} }));
vi.mock('@/server/services/books-import', () => ({ BooksImportService: class {} }));
vi.mock('@/server/services/forecasting', () => ({
  getItemVelocity: vi.fn(),
  suggestReorderPoint: vi.fn(),
}));
vi.mock('@/lib/books/lookup', () => ({ lookupIsbn: vi.fn() }));

import { makeServiceContext, makeSupabaseStub } from '@/test/supabase-mock';

import { draftPosFromForecastSummary, draftPosSummary, TOOL_CATALOG } from './tools';

const ctx = () => makeServiceContext(makeSupabaseStub({}).client) as never;

beforeEach(() => {
  vi.clearAllMocks();
});

describe('draftPosFromForecast', () => {
  it('passes skippedOnOpenPo through and says every below-par item is already on order', async () => {
    autoGenerateDraftPOs.mockResolvedValue({
      createdPoIds: [],
      unassignedCount: 0,
      skipped: 0,
      skippedOnOpenPo: 3,
      supplierFailures: [],
      supplierCount: 0,
    });
    const out = (await TOOL_CATALOG.draftPosFromForecast!.execute({}, ctx())) as {
      skippedOnOpenPo: number;
      summary: string;
    };
    expect(autoGenerateDraftPOs).toHaveBeenCalledWith();
    expect(out.skippedOnOpenPo).toBe(3);
    expect(out.summary).toBe(
      'No drafts created: all 3 below-par items are already on open purchase orders.',
    );
  });

  it('names the skipped count next to the drafts it did create', () => {
    expect(
      draftPosFromForecastSummary({
        createdPoIds: ['a', 'b'],
        unassignedCount: 1,
        skippedOnOpenPo: 1,
        supplierFailures: [],
      }),
    ).toBe(
      'Created 2 draft POs. 1 item on an unassigned draft (set a supplier). 1 below-par item was skipped because already on an open purchase order.',
    );
  });

  it('keeps "nothing below par" for the genuinely empty case', () => {
    expect(
      draftPosFromForecastSummary({
        createdPoIds: [],
        unassignedCount: 0,
        skippedOnOpenPo: 0,
        supplierFailures: [],
      }),
    ).toBe('No drafts created: nothing is below its reorder point.');
  });
});

describe('draftPos', () => {
  it('drafts the matched items and reports how many were already on an open PO', async () => {
    listMock.mockResolvedValue({ total: 2, items: [{ id: 'i-1' }, { id: 'i-2' }] });
    createDraftsFromItems.mockResolvedValue({
      createdPoIds: ['po-1'],
      skipped: 0,
      skippedNoSupplier: 0,
      skippedNotOrderable: 0,
      alreadyOnOpenPo: 2,
      supplierFailures: [],
      supplierCount: 1,
    });
    const out = (await TOOL_CATALOG.draftPos!.execute({}, ctx())) as {
      alreadyOnOpenPo: number | null;
      summary: string;
    };
    // The whole selection goes to the service: nothing is dropped for being on order.
    expect(createDraftsFromItems).toHaveBeenCalledWith(['i-1', 'i-2']);
    expect(out.alreadyOnOpenPo).toBe(2);
    expect(out.summary).toBe(
      'Created 1 draft PO. 2 of the drafted items were already on another open purchase order; review the drafts before sending.',
    );
  });

  it('says it could not check instead of implying none were on order', () => {
    expect(
      draftPosSummary({
        createdPoIds: ['po-1'],
        skippedNoSupplier: 1,
        skippedNotOrderable: 0,
        alreadyOnOpenPo: null,
        supplierFailures: [],
      }),
    ).toBe(
      'Created 1 draft PO. 1 item skipped (no supplier). Could not check whether any of these items are already on open purchase orders.',
    );
  });

  it('never offers a kit\'s pre-assembled stock as a draft candidate (excludeBundles)', async () => {
    listMock.mockResolvedValue({ total: 1, items: [{ id: 'i-1' }] });
    createDraftsFromItems.mockResolvedValue({
      createdPoIds: ['po-1'],
      skipped: 0,
      skippedNoSupplier: 0,
      skippedNotOrderable: 0,
      alreadyOnOpenPo: 0,
      supplierFailures: [],
      supplierCount: 1,
    });
    await TOOL_CATALOG.draftPos!.execute({ lowStock: true }, ctx());
    expect(listMock).toHaveBeenCalledWith(expect.objectContaining({ excludeBundles: true }));
  });

  it('names each reason items were skipped', () => {
    expect(
      draftPosSummary({
        createdPoIds: ['po-1'],
        skippedNoSupplier: 2,
        skippedNotOrderable: 1,
        alreadyOnOpenPo: 0,
        supplierFailures: [],
      }),
    ).toBe(
      'Created 1 draft PO. 2 items skipped (no supplier). 1 item skipped (deleted, or a pre-assembled kit, which is never ordered).',
    );
  });
});

describe('applyReorderPoint', () => {
  it('refuses a kit\'s pre-assembled stock and writes nothing', async () => {
    getMock.mockResolvedValue({ id: 'kit-1', name: 'Reading Kit', is_bundle: true, reorder_point: 0 });
    await expect(
      TOOL_CATALOG.applyReorderPoint!.execute({ itemId: 'kit-1', reorderPoint: 3 }, ctx()),
    ).rejects.toThrow(/pre-assembled stock.*never ordered.*components instead/);
    expect(updateMock).not.toHaveBeenCalled();
  });

  it('still applies a reorder point to an ordinary item', async () => {
    getMock.mockResolvedValue({ id: 'i-1', name: 'Pens', is_bundle: false, reorder_point: 1 });
    updateMock.mockResolvedValue({ id: 'i-1', name: 'Pens', reorder_point: 3, reorder_quantity: null });
    const out = (await TOOL_CATALOG.applyReorderPoint!.execute(
      { itemId: 'i-1', reorderPoint: 3 },
      ctx(),
    )) as { applied: { reorderPoint: number } };
    expect(updateMock).toHaveBeenCalledWith('i-1', { reorderPoint: 3 });
    expect(out.applied.reorderPoint).toBe(3);
  });
});

describe('suggestReorderPoints', () => {
  const suggestion = (id: string) => ({ itemId: id, name: id });

  it('passes a partial review through as truncated, with a note for the model', async () => {
    getReorderSuggestions.mockResolvedValue({
      suggestions: [suggestion('a'), suggestion('b'), suggestion('c')],
      truncated: true,
    });
    const out = (await TOOL_CATALOG.suggestReorderPoints!.execute({ topN: 2 }, ctx())) as {
      total: number;
      returned: number;
      truncated: boolean;
      note?: string;
    };
    expect(out).toMatchObject({ total: 3, returned: 2, truncated: true });
    expect(out.note).toMatch(/partial review/);
  });

  it('says nothing about coverage when the review is complete', async () => {
    getReorderSuggestions.mockResolvedValue({ suggestions: [suggestion('a')], truncated: false });
    const out = (await TOOL_CATALOG.suggestReorderPoints!.execute({}, ctx())) as {
      truncated: boolean;
      note?: string;
    };
    expect(out.truncated).toBe(false);
    expect(out.note).toBeUndefined();
  });
});
