import { beforeEach, describe, expect, it, vi } from 'vitest';

import { makeServiceContext, makeSupabaseStub } from '@/test/supabase-mock';

import { DEFAULT_MODULE_IDS, type ModuleId } from '@stockpilot/core';

// Mock the forecasting engine so we control each item's velocity-derived
// suggestion deterministically (the engine itself is tested elsewhere).
const suggestReorderPoint = vi.fn();
vi.mock('./forecasting', () => ({
  suggestReorderPoint: (...args: unknown[]) => suggestReorderPoint(...args),
}));

// Mock the PO service so we can assert delegation without exercising real PO
// creation (that path is covered by purchase-orders.reorder.test.ts).
const createDraftsFromReorderForecast = vi.fn(async () => ({
  createdPoIds: ['po-1'],
  unassignedCount: 0,
  skipped: 0,
  supplierFailures: [],
  supplierCount: 1,
}));
vi.mock('./purchase-orders', () => ({
  PurchaseOrdersService: class {
    createDraftsFromReorderForecast = createDraftsFromReorderForecast;
  },
}));

import { PlanningService, DEFAULT_PLANNING_PARAMS } from './planning';

/** Module set that INCLUDES planning (an org that opted in). */
const withPlanning = () => new Set<ModuleId>([...DEFAULT_MODULE_IDS, 'planning']);

/** Build a forecast result for a given item id. */
function forecast(
  itemId: string,
  opts: {
    unitsPerDay?: number;
    daysOfStock?: number | null;
    qtyOnHand?: number;
    suggestedReorderPoint?: number;
    suggestedReorderQty?: number;
    currentReorderPoint?: number;
  } = {},
) {
  return {
    itemId,
    suggestedReorderPoint: opts.suggestedReorderPoint ?? 0,
    suggestedReorderQty: opts.suggestedReorderQty ?? 0,
    currentReorderPoint: opts.currentReorderPoint ?? 0,
    currentReorderQty: 0,
    leadTimeDays: 14,
    safetyMultiplier: 1.5,
    rationale: 'test',
    velocity: {
      itemId,
      unitsOutPerDay: opts.unitsPerDay ?? 0,
      unitsOutTotal: 0,
      windowDays: 90,
      quantityOnHand: opts.qtyOnHand ?? 0,
      daysOfStockRemaining: opts.daysOfStock ?? null,
      projectedRunoutAt: null,
    },
  };
}

beforeEach(() => {
  vi.clearAllMocks();
});

describe('PlanningService gating', () => {
  it('getReorderSuggestions throws module_disabled when planning is off', async () => {
    const stub = makeSupabaseStub({});
    // Default module set (charter pack) does NOT include planning.
    const svc = new PlanningService(makeServiceContext(stub.client));
    await expect(svc.getReorderSuggestions()).rejects.toMatchObject({ code: 'module_disabled' });
    expect(suggestReorderPoint).not.toHaveBeenCalled();
  });

  it('getReorderSuggestions throws forbidden when role lacks purchase_orders:manage', async () => {
    const stub = makeSupabaseStub({});
    const svc = new PlanningService(
      makeServiceContext(stub.client, { enabledModules: withPlanning(), role: 'viewer' }),
    );
    await expect(svc.getReorderSuggestions()).rejects.toMatchObject({ code: 'forbidden' });
  });

  it('autoGenerateDraftPOs throws module_disabled when planning is off (no delegation)', async () => {
    const stub = makeSupabaseStub({});
    const svc = new PlanningService(makeServiceContext(stub.client));
    await expect(svc.autoGenerateDraftPOs()).rejects.toMatchObject({ code: 'module_disabled' });
    expect(createDraftsFromReorderForecast).not.toHaveBeenCalled();
  });
});

describe('PlanningService.readParams', () => {
  it('returns defaults when no settings row exists', async () => {
    const stub = makeSupabaseStub({
      'organization_modules.select': { data: null, error: null },
    });
    const svc = new PlanningService(makeServiceContext(stub.client, { enabledModules: withPlanning() }));
    await expect(svc.readParams()).resolves.toEqual(DEFAULT_PLANNING_PARAMS);
  });

  it('returns defaults for garbage/missing values and reads valid overrides', async () => {
    const stub = makeSupabaseStub({
      'organization_modules.select': {
        data: { settings: { leadTimeDays: 30, safetyMultiplier: 'oops', velocityWindowDays: -5 } },
        error: null,
      },
    });
    const svc = new PlanningService(makeServiceContext(stub.client, { enabledModules: withPlanning() }));
    const params = await svc.readParams();
    expect(params.leadTimeDays).toBe(30); // valid override
    expect(params.safetyMultiplier).toBe(DEFAULT_PLANNING_PARAMS.safetyMultiplier); // garbage -> default
    expect(params.velocityWindowDays).toBe(DEFAULT_PLANNING_PARAMS.velocityWindowDays); // <=0 -> default
  });
});

describe('PlanningService.getReorderSuggestions', () => {
  it('composes suggestions from forecasting and sorts by urgency (lowest cover first)', async () => {
    const items = [
      { id: 'item-a', sku: 'A', name: 'Alpha', quantity_on_hand: 5, reorder_point: 2, unit_cost: 3, supplier_id: 'sup-1' },
      { id: 'item-b', sku: 'B', name: 'Bravo', quantity_on_hand: 20, reorder_point: 4, unit_cost: 1, supplier_id: null },
      { id: 'item-c', sku: 'C', name: 'Charlie', quantity_on_hand: 0, reorder_point: 0, unit_cost: 2, supplier_id: 'sup-1' },
    ];
    const stub = makeSupabaseStub({
      'organization_modules.select': { data: { settings: {} }, error: null },
      'inventory_items.select': { data: items, error: null },
      'suppliers.select': { data: [{ id: 'sup-1', name: 'Supplier One' }], error: null },
    });

    // item-a: 10 days cover. item-b: 40 days cover. item-c: no movement (null).
    suggestReorderPoint.mockImplementation(async (_sb, _org, itemId) => {
      if (itemId === 'item-a')
        return forecast('item-a', { unitsPerDay: 0.5, daysOfStock: 10, qtyOnHand: 5, suggestedReorderPoint: 11 });
      if (itemId === 'item-b')
        return forecast('item-b', { unitsPerDay: 0.5, daysOfStock: 40, qtyOnHand: 20, suggestedReorderPoint: 11 });
      return forecast('item-c', { unitsPerDay: 0, daysOfStock: null, qtyOnHand: 0, suggestedReorderPoint: 0 });
    });

    const svc = new PlanningService(makeServiceContext(stub.client, { enabledModules: withPlanning() }));
    const result = await svc.getReorderSuggestions();

    // Order: lowest cover first -> a (10), b (40), then non-moving c (null).
    expect(result.map((r) => r.itemId)).toEqual(['item-a', 'item-b', 'item-c']);

    // Composed fields are carried through from forecasting + the item row.
    const a = result[0]!;
    expect(a.sku).toBe('A');
    expect(a.name).toBe('Alpha');
    expect(a.supplierName).toBe('Supplier One');
    expect(a.unitsPerDay).toBe(0.5);
    expect(a.daysOfStockRemaining).toBe(10);
    expect(a.suggestedReorderPoint).toBe(11);
    expect(a.unitCost).toBe(3);

    // No-supplier item carries a null supplierName.
    expect(result.find((r) => r.itemId === 'item-b')?.supplierName).toBeNull();

    // Forecasting was asked with the resolved (default) params.
    expect(suggestReorderPoint).toHaveBeenCalledTimes(3);
    const passedOpts = suggestReorderPoint.mock.calls[0]![3];
    expect(passedOpts).toEqual({
      leadTimeDays: DEFAULT_PLANNING_PARAMS.leadTimeDays,
      safetyMultiplier: DEFAULT_PLANNING_PARAMS.safetyMultiplier,
      windowDays: DEFAULT_PLANNING_PARAMS.velocityWindowDays,
    });
  });

  it('returns [] when there are no candidate items', async () => {
    const stub = makeSupabaseStub({
      'organization_modules.select': { data: { settings: {} }, error: null },
      'inventory_items.select': { data: [], error: null },
    });
    const svc = new PlanningService(makeServiceContext(stub.client, { enabledModules: withPlanning() }));
    await expect(svc.getReorderSuggestions()).resolves.toEqual([]);
    expect(suggestReorderPoint).not.toHaveBeenCalled();
  });
});

describe('PlanningService.autoGenerateDraftPOs', () => {
  it('delegates to PurchaseOrdersService.createDraftsFromReorderForecast and returns its result', async () => {
    const stub = makeSupabaseStub({});
    const svc = new PlanningService(makeServiceContext(stub.client, { enabledModules: withPlanning() }));
    const result = await svc.autoGenerateDraftPOs();
    expect(createDraftsFromReorderForecast).toHaveBeenCalledTimes(1);
    expect(result).toEqual({
      createdPoIds: ['po-1'],
      unassignedCount: 0,
      skipped: 0,
      supplierFailures: [],
      supplierCount: 1,
    });
  });
});
