import { beforeEach, describe, expect, it, vi } from 'vitest';

import {
  callArgs,
  makeServiceContext,
  makeSupabaseStub,
  servedLikePostgrest,
  type MockCall,
} from '@/test/supabase-mock';

import { DEFAULT_MODULE_IDS, type ModuleId } from '@stockpilot/core';

// Mock the forecasting engine so we control each item's velocity-derived
// suggestion deterministically (the engine itself is tested elsewhere).
// The service now uses the bulk velocity path (one query) + the pure reorder
// math, so we mock both seams.
const getBulkItemVelocities = vi.fn();
const computeReorderSuggestion = vi.fn();
vi.mock('./forecasting', () => ({
  getBulkItemVelocities: (...args: unknown[]) => getBulkItemVelocities(...args),
  computeReorderSuggestion: (...args: unknown[]) => computeReorderSuggestion(...args),
}));

// Mock the PO service so we can assert delegation without exercising real PO
// creation (that path is covered by purchase-orders.reorder.test.ts).
const createDraftsFromReorderForecast = vi.fn(async () => ({
  createdPoIds: ['po-1'],
  unassignedCount: 0,
  skipped: 0,
  skippedOnOpenPo: 3,
  supplierFailures: [],
  supplierCount: 1,
}));
const listOpenPoItemIds = vi.fn(async () => new Set(['item-on-order']));
vi.mock('./purchase-orders', () => ({
  PurchaseOrdersService: class {
    createDraftsFromReorderForecast = createDraftsFromReorderForecast;
    listOpenPoItemIds = listOpenPoItemIds;
  },
}));

import { PlanningService, DEFAULT_PLANNING_PARAMS, PLANNING_MAX_ITEMS } from './planning';

/** Module set that INCLUDES planning (an org that opted in). */
const withPlanning = () => new Set<ModuleId>([...DEFAULT_MODULE_IDS, 'planning']);

/** Build a velocity snapshot for a given item id (bulk-velocity result). */
function velocity(
  itemId: string,
  opts: { unitsPerDay?: number; daysOfStock?: number | null; qtyOnHand?: number } = {},
) {
  return {
    itemId,
    unitsOutPerDay: opts.unitsPerDay ?? 0,
    unitsOutTotal: 0,
    windowDays: 90,
    quantityOnHand: opts.qtyOnHand ?? 0,
    daysOfStockRemaining: opts.daysOfStock ?? null,
    projectedRunoutAt: null,
  };
}

/** Build a forecast (ReorderSuggestion) result for a given velocity snapshot. */
function forecast(
  v: ReturnType<typeof velocity>,
  opts: { suggestedReorderPoint?: number; suggestedReorderQty?: number; currentReorderPoint?: number } = {},
) {
  return {
    itemId: v.itemId,
    suggestedReorderPoint: opts.suggestedReorderPoint ?? 0,
    suggestedReorderQty: opts.suggestedReorderQty ?? 0,
    currentReorderPoint: opts.currentReorderPoint ?? 0,
    currentReorderQty: 0,
    leadTimeDays: 14,
    safetyMultiplier: 1.5,
    rationale: 'test',
    velocity: v,
  };
}

beforeEach(() => {
  vi.clearAllMocks();
});

describe('PlanningService gating', () => {
  it('getReorderSuggestions throws module_disabled when planning is off', async () => {
    const stub = makeSupabaseStub({});
    // Default module set (charter pack) does NOT include planning.
    const svc = new PlanningService(makeServiceContext(stub.client));
    await expect(svc.getReorderSuggestions()).rejects.toMatchObject({ code: 'module_disabled' });
    expect(getBulkItemVelocities).not.toHaveBeenCalled();
  });

  it('getReorderSuggestions throws forbidden when role lacks purchase_orders:manage', async () => {
    const stub = makeSupabaseStub({});
    const svc = new PlanningService(
      makeServiceContext(stub.client, { enabledModules: withPlanning(), role: 'viewer' }),
    );
    await expect(svc.getReorderSuggestions()).rejects.toMatchObject({ code: 'forbidden' });
  });

  it('autoGenerateDraftPOs throws module_disabled when planning is off (no delegation)', async () => {
    const stub = makeSupabaseStub({});
    const svc = new PlanningService(makeServiceContext(stub.client));
    await expect(svc.autoGenerateDraftPOs()).rejects.toMatchObject({ code: 'module_disabled' });
    expect(createDraftsFromReorderForecast).not.toHaveBeenCalled();
  });

  it('getReorderSuggestions enforces the purchase_orders dependsOn contract', async () => {
    const stub = makeSupabaseStub({});
    // planning ON but purchase_orders OFF — a malformed/partial-cascade state.
    const modules = new Set<ModuleId>(
      ([...DEFAULT_MODULE_IDS, 'planning'] as ModuleId[]).filter((m) => m !== 'purchase_orders'),
    );
    const svc = new PlanningService(makeServiceContext(stub.client, { enabledModules: modules }));
    await expect(svc.getReorderSuggestions()).rejects.toMatchObject({ code: 'module_disabled' });
    expect(getBulkItemVelocities).not.toHaveBeenCalled();
  });
});

describe('PlanningService.readParams', () => {
  it('returns defaults when no settings row exists', async () => {
    const stub = makeSupabaseStub({
      'organization_modules.select': { data: null, error: null },
    });
    const svc = new PlanningService(makeServiceContext(stub.client, { enabledModules: withPlanning() }));
    await expect(svc.readParams()).resolves.toEqual(DEFAULT_PLANNING_PARAMS);
  });

  it('returns defaults for garbage/missing values and reads valid overrides', async () => {
    const stub = makeSupabaseStub({
      'organization_modules.select': {
        data: { settings: { leadTimeDays: 30, safetyMultiplier: 'oops', velocityWindowDays: -5 } },
        error: null,
      },
    });
    const svc = new PlanningService(makeServiceContext(stub.client, { enabledModules: withPlanning() }));
    const params = await svc.readParams();
    expect(params.leadTimeDays).toBe(30); // valid override
    expect(params.safetyMultiplier).toBe(DEFAULT_PLANNING_PARAMS.safetyMultiplier); // garbage -> default
    expect(params.velocityWindowDays).toBe(DEFAULT_PLANNING_PARAMS.velocityWindowDays); // <=0 -> default
  });

  it('fails CLOSED to defaults on a settings query error (never throws)', async () => {
    const stub = makeSupabaseStub({
      'organization_modules.select': {
        data: null,
        error: { message: 'connection reset' },
      },
    });
    const svc = new PlanningService(makeServiceContext(stub.client, { enabledModules: withPlanning() }));
    // Contract is "never throws on a bad value" — a transient query error is
    // just another bad value, so we return defaults instead of bubbling up.
    await expect(svc.readParams()).resolves.toEqual(DEFAULT_PLANNING_PARAMS);
  });
});

describe('PlanningService.getReorderSuggestions', () => {
  it('composes suggestions from forecasting and sorts by urgency (lowest cover first)', async () => {
    const created = '2020-01-01T00:00:00.000Z';
    const items = [
      { id: 'item-a', sku: 'A', name: 'Alpha', quantity_on_hand: 5, reorder_point: 2, reorder_quantity: 0, unit_cost: 3, supplier_id: 'sup-1', created_at: created },
      { id: 'item-b', sku: 'B', name: 'Bravo', quantity_on_hand: 20, reorder_point: 4, reorder_quantity: 0, unit_cost: 1, supplier_id: null, created_at: created },
      { id: 'item-c', sku: 'C', name: 'Charlie', quantity_on_hand: 0, reorder_point: 0, reorder_quantity: 0, unit_cost: 2, supplier_id: 'sup-1', created_at: created },
    ];
    const stub = makeSupabaseStub({
      'organization_modules.select': { data: { settings: {} }, error: null },
      'inventory_items.select': { data: items, error: null },
      'suppliers.select': { data: [{ id: 'sup-1', name: 'Supplier One' }], error: null },
    });

    // item-a: 10 days cover. item-b: 40 days cover. item-c: no movement (null).
    const velA = velocity('item-a', { unitsPerDay: 0.5, daysOfStock: 10, qtyOnHand: 5 });
    const velB = velocity('item-b', { unitsPerDay: 0.5, daysOfStock: 40, qtyOnHand: 20 });
    const velC = velocity('item-c', { unitsPerDay: 0, daysOfStock: null, qtyOnHand: 0 });
    getBulkItemVelocities.mockResolvedValue(
      new Map([
        ['item-a', velA],
        ['item-b', velB],
        ['item-c', velC],
      ]),
    );
    computeReorderSuggestion.mockImplementation((v) => {
      if (v.itemId === 'item-a') return forecast(velA, { suggestedReorderPoint: 11 });
      if (v.itemId === 'item-b') return forecast(velB, { suggestedReorderPoint: 11 });
      return forecast(velC, { suggestedReorderPoint: 0 });
    });

    const svc = new PlanningService(makeServiceContext(stub.client, { enabledModules: withPlanning() }));
    const { suggestions: result, truncated } = await svc.getReorderSuggestions();
    expect(truncated).toBe(false);

    // Order: lowest cover first -> a (10), b (40), then non-moving c (null).
    expect(result.map((r) => r.itemId)).toEqual(['item-a', 'item-b', 'item-c']);

    // Composed fields are carried through from forecasting + the item row.
    const a = result[0]!;
    expect(a.sku).toBe('A');
    expect(a.name).toBe('Alpha');
    expect(a.supplierName).toBe('Supplier One');
    expect(a.unitsPerDay).toBe(0.5);
    expect(a.daysOfStockRemaining).toBe(10);
    expect(a.suggestedReorderPoint).toBe(11);
    expect(a.unitCost).toBe(3);

    // No-supplier item carries a null supplierName.
    expect(result.find((r) => r.itemId === 'item-b')?.supplierName).toBeNull();

    // Velocity was computed in ONE bulk call (no per-item fan-out).
    expect(getBulkItemVelocities).toHaveBeenCalledTimes(1);
    expect(getBulkItemVelocities.mock.calls[0]![3]).toBe(DEFAULT_PLANNING_PARAMS.velocityWindowDays);
    // The reorder formula was applied per item with the resolved (default) params.
    expect(computeReorderSuggestion).toHaveBeenCalledTimes(3);
    expect(computeReorderSuggestion.mock.calls[0]![3]).toEqual({
      leadTimeDays: DEFAULT_PLANNING_PARAMS.leadTimeDays,
      safetyMultiplier: DEFAULT_PLANNING_PARAMS.safetyMultiplier,
    });
  });

  it('returns [] when there are no candidate items', async () => {
    const stub = makeSupabaseStub({
      'organization_modules.select': { data: { settings: {} }, error: null },
      'inventory_items.select': { data: [], error: null },
    });
    const svc = new PlanningService(makeServiceContext(stub.client, { enabledModules: withPlanning() }));
    await expect(svc.getReorderSuggestions()).resolves.toEqual({ suggestions: [], truncated: false });
    expect(getBulkItemVelocities).not.toHaveBeenCalled();
  });

  it('paginates the candidate fetch past the 1000-row PostgREST cap', async () => {
    // The Data API clamps any single response to max_rows=1000. A candidate set
    // of 2300 items must therefore be assembled across .range() pages — the old
    // .limit(5000) silently returned only the first 1000, so items past 1000 got
    // NO reorder suggestion. Hand the stub successive 1000-row pages.
    const PAGE = 1000;
    const TOTAL = 2300;
    let page = 0;
    const stub = makeSupabaseStub({
      'organization_modules.select': { data: { settings: {} }, error: null },
      'inventory_items.select': () => {
        const start = page * PAGE;
        const rows: Record<string, unknown>[] = [];
        for (let i = start; i < Math.min(start + PAGE, TOTAL); i += 1) {
          rows.push({
            id: `item-${i.toString().padStart(6, '0')}`,
            sku: `S${i}`,
            name: `Item ${i}`,
            quantity_on_hand: 1,
            reorder_point: 5,
            reorder_quantity: 0,
            unit_cost: 1,
            supplier_id: null,
            created_at: '2020-01-01T00:00:00.000Z',
          });
        }
        page += 1;
        return { data: rows, error: null };
      },
      'suppliers.select': { data: [], error: null },
    });
    // Velocity + forecast: every item is a flat passthrough; the assertion is
    // about completeness of the candidate set, not the math.
    getBulkItemVelocities.mockImplementation(async (_s, _o, items: Array<{ id: string }>) => {
      const m = new Map<string, ReturnType<typeof velocity>>();
      for (const it of items) m.set(it.id, velocity(it.id, { unitsPerDay: 1, daysOfStock: 1 }));
      return m;
    });
    computeReorderSuggestion.mockImplementation((v: ReturnType<typeof velocity>) =>
      forecast(v, { suggestedReorderPoint: 5 }),
    );

    const svc = new PlanningService(makeServiceContext(stub.client, { enabledModules: withPlanning() }));
    const { suggestions: result, truncated } = await svc.getReorderSuggestions();

    // All 2300 candidates surfaced — not just the first 1000.
    expect(result).toHaveLength(TOTAL);
    expect(truncated).toBe(false);
    expect(result.some((r) => r.itemId === 'item-002299')).toBe(true);
    // At least three .range() pages were issued (1000 + 1000 + 300).
    const ranges = stub.chainArgsAll.get('inventory_items.select') ?? [];
    expect(ranges.length).toBeGreaterThanOrEqual(3);
  });
});

// ─── The candidate set: the shared reorder-candidate predicate (S3) ───────────

/** A planning candidate row as the database holds it (the filter columns included). */
const planRow = (id: string, over: Record<string, unknown> = {}) => ({
  id,
  sku: id.toUpperCase(),
  name: `Item ${id}`,
  quantity_on_hand: 1,
  reorder_point: 0,
  reorder_quantity: 0,
  unit_cost: 1,
  supplier_id: null,
  created_at: '2020-01-01T00:00:00.000Z',
  organization_id: 'org-test',
  deleted_at: null,
  status: 'active',
  is_rental: false,
  is_bundle: false,
  ...over,
});

/** Velocity and forecast mocks that pass every item through. */
function passThroughForecasting() {
  getBulkItemVelocities.mockImplementation(async (_s, _o, items: Array<{ id: string }>) => {
    const m = new Map<string, ReturnType<typeof velocity>>();
    for (const it of items) m.set(it.id, velocity(it.id, { unitsPerDay: 1, daysOfStock: 3 }));
    return m;
  });
  computeReorderSuggestion.mockImplementation((v: ReturnType<typeof velocity>) =>
    forecast(v, { suggestedReorderPoint: 5 }),
  );
}

describe('PlanningService.getReorderSuggestions — which items are planned', () => {
  it('reads with the shared predicate: never a kit\'s pre-assembled stock, a rental, a deleted or an inactive item', async () => {
    const stub = makeSupabaseStub({
      'organization_modules.select': { data: { settings: {} }, error: null },
      'inventory_items.select': { data: [], error: null },
    });
    const svc = new PlanningService(makeServiceContext(stub.client, { enabledModules: withPlanning() }));
    await svc.getReorderSuggestions();

    const methods = stub.chainsAll.get('inventory_items.select')![0]!;
    const args = stub.chainArgsAll.get('inventory_items.select')![0]!;
    const filters = methods.map((m, i) => [m, ...(args[i] ?? [])]);
    expect(filters).toContainEqual(['eq', 'is_bundle', false]);
    expect(filters).toContainEqual(['eq', 'is_rental', false]);
    expect(filters).toContainEqual(['is', 'deleted_at', null]);
    expect(filters).toContainEqual(['eq', 'status', 'active']);
    expect(filters).toContainEqual(['eq', 'organization_id', 'org-test']);
    // Planning ranks items with no reorder point too (it suggests one).
    expect(methods).not.toContain('gt');
  });

  it('a kit\'s pre-assembled stock below par is not on the plan (the stub answers like the database)', async () => {
    const stub = makeSupabaseStub({
      'organization_modules.select': { data: { settings: {} }, error: null },
      'inventory_items.select': servedLikePostgrest([
        planRow('plain', { reorder_point: 5 }),
        planRow('kit', { is_bundle: true, reorder_point: 3, quantity_on_hand: 0 }),
        planRow('rental', { is_rental: true }),
      ]),
      'suppliers.select': { data: [], error: null },
    });
    passThroughForecasting();
    const svc = new PlanningService(makeServiceContext(stub.client, { enabledModules: withPlanning() }));

    const { suggestions } = await svc.getReorderSuggestions();

    expect(suggestions.map((s) => s.itemId)).toEqual(['plain']);
  });
});

describe('PlanningService.getReorderSuggestions — a catalog past the cap says so', () => {
  /** A stub serving `total` candidate rows by the query's own .range() window. */
  function catalogOf(total: number) {
    return makeSupabaseStub({
      'organization_modules.select': { data: { settings: {} }, error: null },
      'inventory_items.select': (call: MockCall) => {
        const [from, to] = callArgs(call, 'range') as [number, number];
        const rows: Array<ReturnType<typeof planRow>> = [];
        for (let i = from; i <= Math.min(to, from + 999, total - 1); i += 1) {
          rows.push(planRow(`item-${String(i).padStart(6, '0')}`));
        }
        return { data: rows, error: null };
      },
      'suppliers.select': { data: [], error: null },
    });
  }

  it(`${PLANNING_MAX_ITEMS + 1} candidates: truncated, and exactly ${PLANNING_MAX_ITEMS} ranked`, async () => {
    passThroughForecasting();
    const stub = catalogOf(PLANNING_MAX_ITEMS + 1);
    const svc = new PlanningService(makeServiceContext(stub.client, { enabledModules: withPlanning() }));

    const { suggestions, truncated } = await svc.getReorderSuggestions();

    expect(truncated).toBe(true);
    expect(suggestions).toHaveLength(PLANNING_MAX_ITEMS);
    // The sentinel row (the one past the cap) is never ranked.
    expect(suggestions.some((s) => s.itemId === `item-${String(PLANNING_MAX_ITEMS).padStart(6, '0')}`)).toBe(false);
    // ... and velocity is computed for the ranked items only.
    expect((getBulkItemVelocities.mock.calls[0]![2] as unknown[]).length).toBe(PLANNING_MAX_ITEMS);
  });

  it(`exactly ${PLANNING_MAX_ITEMS} candidates: complete, not truncated`, async () => {
    passThroughForecasting();
    const stub = catalogOf(PLANNING_MAX_ITEMS);
    const svc = new PlanningService(makeServiceContext(stub.client, { enabledModules: withPlanning() }));

    const { suggestions, truncated } = await svc.getReorderSuggestions();

    expect(truncated).toBe(false);
    expect(suggestions).toHaveLength(PLANNING_MAX_ITEMS);
  });
});

describe('PlanningService.autoGenerateDraftPOs', () => {
  it('delegates to PurchaseOrdersService.createDraftsFromReorderForecast and returns its result', async () => {
    const stub = makeSupabaseStub({});
    const svc = new PlanningService(makeServiceContext(stub.client, { enabledModules: withPlanning() }));
    const result = await svc.autoGenerateDraftPOs();
    expect(createDraftsFromReorderForecast).toHaveBeenCalledTimes(1);
    // Takes no arguments (the ignored itemIds parameter is gone) and passes
    // the service result through, including the open-PO skip count.
    expect(createDraftsFromReorderForecast).toHaveBeenCalledWith();
    expect(result).toEqual({
      createdPoIds: ['po-1'],
      unassignedCount: 0,
      skipped: 0,
      skippedOnOpenPo: 3,
      supplierFailures: [],
      supplierCount: 1,
    });
  });
});

describe('PlanningService.itemIdsOnOpenPurchaseOrders', () => {
  it('delegates to the PO service open-PO read (the set the draft button skips)', async () => {
    const stub = makeSupabaseStub({});
    const svc = new PlanningService(makeServiceContext(stub.client, { enabledModules: withPlanning() }));
    await expect(svc.itemIdsOnOpenPurchaseOrders()).resolves.toEqual(new Set(['item-on-order']));
    expect(listOpenPoItemIds).toHaveBeenCalledTimes(1);
  });

  it('propagates a failed read (the page decides how to say so; never an empty set)', async () => {
    listOpenPoItemIds.mockRejectedValueOnce(new Error('read failed'));
    const stub = makeSupabaseStub({});
    const svc = new PlanningService(makeServiceContext(stub.client, { enabledModules: withPlanning() }));
    await expect(svc.itemIdsOnOpenPurchaseOrders()).rejects.toThrow('read failed');
  });

  it('is gated on the planning module', async () => {
    const stub = makeSupabaseStub({});
    const svc = new PlanningService(makeServiceContext(stub.client));
    await expect(svc.itemIdsOnOpenPurchaseOrders()).rejects.toMatchObject({ code: 'module_disabled' });
    expect(listOpenPoItemIds).not.toHaveBeenCalled();
  });
});
