#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────
# dev-local.sh — point the web app at the local Supabase Docker stack.
#
# Idempotent. Safe to run any time:
#   • Backs up the current apps/web/.env.local to .env.local.prod if no
#     backup exists yet.
#   • Boots `supabase start` (no-op if already running).
#   • Writes apps/web/.env.local for the local stack, preserving the
#     real third-party API keys (Gemini / Resend / Stripe) so AI + email
#     features keep working.
#   • Starts `pnpm --filter @stockpilot/web dev`.
#
# To return to hosted prod, run scripts/dev-prod.sh.
# ─────────────────────────────────────────────────────────────────────────
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WEB_ENV="$ROOT/apps/web/.env.local"
WEB_ENV_PROD="$ROOT/apps/web/.env.local.prod"

if [ ! -f "$WEB_ENV_PROD" ]; then
  if [ -f "$WEB_ENV" ]; then
    echo "→ Backing up current $WEB_ENV to $WEB_ENV_PROD"
    cp "$WEB_ENV" "$WEB_ENV_PROD"
  else
    echo "⚠  No existing $WEB_ENV to back up. dev-prod.sh will fail until you write one."
  fi
fi

echo "→ Ensuring Docker daemon is up"
if ! docker info >/dev/null 2>&1; then
  echo "  Docker isn't running. Launch Docker Desktop and try again."
  exit 1
fi

echo "→ supabase start (no-op if already running)"
cd "$ROOT"
supabase start

# Pull the local anon + service-role JWT keys from supabase status —env so
# we always write the values matching the running stack (Supabase rotates
# them per project_id).
STATUS_ENV="$(supabase status --output env 2>/dev/null)"
LOCAL_ANON="$(echo "$STATUS_ENV" | grep '^ANON_KEY=' | sed 's/^ANON_KEY=//;s/^"//;s/"$//')"
LOCAL_SERVICE="$(echo "$STATUS_ENV" | grep '^SERVICE_ROLE_KEY=' | sed 's/^SERVICE_ROLE_KEY=//;s/^"//;s/"$//')"

if [ -z "$LOCAL_ANON" ] || [ -z "$LOCAL_SERVICE" ]; then
  echo "✗ Failed to read local Supabase keys from 'supabase status --output env'."
  exit 1
fi

# Pull third-party keys from the prod backup so AI / email keep working.
THIRD_PARTY_KEYS=""
if [ -f "$WEB_ENV_PROD" ]; then
  for k in GEMINI_API_KEY RESEND_API_KEY STRIPE_SECRET_KEY STRIPE_WEBHOOK_SECRET NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY; do
    v="$(grep "^${k}=" "$WEB_ENV_PROD" 2>/dev/null | sed "s/^${k}=//")"
    THIRD_PARTY_KEYS+="${k}=${v}"$'\n'
  done
fi

echo "→ Writing $WEB_ENV pointing at local Supabase"
cat > "$WEB_ENV" <<EOF
# ============================================================================
# LOCAL DEV — generated by scripts/dev-local.sh. Re-run that script to
# refresh the Supabase keys after 'supabase stop' + 'supabase start'.
# Hosted prod credentials live in .env.local.prod (run dev-prod.sh to swap).
# ============================================================================

NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_SITE_NAME=StockPilot

# ── Supabase local stack (Docker, 127.0.0.1) ──────────────────────────────
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=${LOCAL_ANON}
SUPABASE_SERVICE_ROLE_KEY=${LOCAL_SERVICE}

# ── Third-party APIs — copied from .env.local.prod, still hit real services ──
${THIRD_PARTY_KEYS}
EOF

echo ""
echo "✓ Local dev ready."
echo "  Supabase Studio:  http://127.0.0.1:54323"
echo "  Mail catcher:     http://127.0.0.1:54324  (Supabase Auth emails land here)"
echo "  Web app:          http://localhost:3000"
echo ""
echo "→ Starting pnpm --filter @stockpilot/web dev"
exec pnpm --filter @stockpilot/web dev
