-- ============================================================================
-- SHIPMENTS — outbound packing slips
-- ============================================================================
-- Tracks a shipment from one warehouse to another. The packing slip PDF is
-- one *output* of a shipment row; the row itself is the system of record
-- for what was shipped, when, by whom, who signed for it, and where the
-- signed PDF was emailed. Optionally linked to an order_request when the
-- shipment fulfills an internal request (the 99% case for L4L).
-- ============================================================================

create table public.shipments (
  id                          uuid primary key default gen_random_uuid(),
  organization_id             uuid not null references public.organizations(id) on delete cascade,

  -- The two warehouses involved. source ships, destination receives.
  source_warehouse_id         uuid not null references public.warehouses(id) on delete restrict,
  destination_warehouse_id    uuid not null references public.warehouses(id) on delete restrict,

  -- Optional link to the request that triggered this shipment. Multiple
  -- shipments can fulfill one request (partial deliveries) so this is
  -- not unique.
  order_request_id            uuid references public.order_requests(id) on delete set null,

  -- Auto-generated by the service: ISR-{destination.code}-{MMDDYYYY}.
  -- Unique per org so a school never sees two slips with the same WO#.
  work_order_number           text not null,

  ship_date                   date not null default current_date,
  attention_to_name           text,
  notes                       text,

  status                      text not null default 'draft'
                                check (status in ('draft','shipped','delivered','cancelled')),

  -- Signature state — populated by the public /s/[token] page.
  signature_image_url         text,
  signed_by_name              text,
  signed_at                   timestamptz,

  -- Public token drives the QR code / unauthed signature page. Long random
  -- string set at creation; expires 7 days after creation by convention
  -- (enforced server-side, not via DB constraint).
  signature_token             text unique,
  signature_token_expires_at  timestamptz,

  -- Where the signed PDF gets emailed when the recipient signs. The
  -- recipient types their own email on the signature page; CC emails
  -- (school principal etc.) can be set by the warehouse staff at
  -- shipment-creation time. Source warehouse manager is always cc'd
  -- automatically — no need to store that here.
  signature_email_to          text,
  signature_email_cc          text[],

  created_by                  uuid references public.user_profiles(id) on delete set null,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now(),

  unique (organization_id, work_order_number)
);

create trigger shipments_set_updated_at
  before update on public.shipments
  for each row execute function public.tg_set_updated_at();

create index shipments_org_status_idx
  on public.shipments(organization_id, status, ship_date desc);
create index shipments_destination_idx
  on public.shipments(destination_warehouse_id, ship_date desc);
create index shipments_source_idx
  on public.shipments(source_warehouse_id, ship_date desc);
create index shipments_order_request_idx
  on public.shipments(order_request_id)
  where order_request_id is not null;

-- ============================================================================

create table public.shipment_lines (
  id                  uuid primary key default gen_random_uuid(),
  shipment_id         uuid not null references public.shipments(id) on delete cascade,
  organization_id     uuid not null references public.organizations(id) on delete cascade,

  item_id             uuid not null references public.inventory_items(id) on delete restrict,

  qty_shipped         numeric(14,3) not null check (qty_shipped >= 0),
  qty_back_ordered    numeric(14,3) not null default 0 check (qty_back_ordered >= 0),

  -- Render order on the slip; the service sets this to keep printing
  -- consistent across views.
  line_order          int not null default 0,

  created_at          timestamptz not null default now()
);

create index shipment_lines_shipment_idx
  on public.shipment_lines(shipment_id, line_order);
create index shipment_lines_item_idx
  on public.shipment_lines(item_id);

-- ============================================================================
-- RLS — same shape as purchase_orders. Members can read, managers+ can
-- write. The public signature page uses the admin client (service role)
-- with token verification, so no anon policy is needed here.
-- ============================================================================

alter table public.shipments enable row level security;
alter table public.shipment_lines enable row level security;

create policy shipments_select on public.shipments
  for select to authenticated
  using (public.is_org_member(organization_id));
create policy shipments_write on public.shipments
  for all to authenticated
  using (public.has_org_role(organization_id, 'manager'))
  with check (public.has_org_role(organization_id, 'manager'));

create policy shipment_lines_select on public.shipment_lines
  for select to authenticated
  using (public.is_org_member(organization_id));
create policy shipment_lines_write on public.shipment_lines
  for all to authenticated
  using (public.has_org_role(organization_id, 'manager'))
  with check (public.has_org_role(organization_id, 'manager'));
