-- 0103_mfa_recovery_normalize.sql
-- ============================================================================
-- Fix the recovery-code hashing input normalization so the client can be
-- liberal about whitespace, case, and the dash separator without locking
-- the user out.
--
-- Previously (`0027_mfa_recovery_codes.sql`):
--   hashed := encode(extensions.digest(upper(trim(p_code)), 'sha256'), 'hex');
--
-- That left dashes inside the input. If the user pastes the code without
-- dashes (`ABCD1234EFGH5678`) or with extra spaces inside (`ABCD - 1234 -
-- EFGH - 5678`), the hash never matched and a valid code looked invalid —
-- which is the worst possible UX during an MFA lockout.
--
-- New canonicalization: strip every non-alphanumeric character and
-- uppercase, then hash. The matching is computed against the same
-- canonical form, since the generator stores a `groupA-groupB-groupC-
-- groupD` plaintext whose A-Z0-9 characters survive the strip exactly.
-- The CHANGE is hash-input-side only — we never re-hash existing rows.
--
-- This means existing rows generated by 0027 with the old hash will
-- ALSO continue to match because the canonical form of the original
-- plaintext (`ABCD-1234-EFGH-5678`) under the new function is
-- `ABCD1234EFGH5678`, while the old stored hash was over the
-- WITH-dashes form. To keep both populations working, the function
-- tries the new canonical form first, then falls back to the legacy
-- "upper(trim)" form. Rows generated AFTER this migration are stored
-- only against the new (stripped) form by the updated generator.
-- ============================================================================

create or replace function public.generate_mfa_recovery_codes()
returns table(code text)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  uid uuid := auth.uid();
  i int;
  raw_code text;
  canonical text;
  alphabet text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  group_a text;
  group_b text;
  group_c text;
  group_d text;
  pos int;
begin
  if uid is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  delete from public.mfa_recovery_codes where user_id = uid;

  for i in 1..10 loop
    -- 16 chars from a 32-char alphabet → ~80 bits of entropy.
    group_a := '';
    group_b := '';
    group_c := '';
    group_d := '';
    for pos in 1..4 loop
      group_a := group_a || substring(alphabet
        from (1 + (get_byte(extensions.gen_random_bytes(1), 0) % 32))::int for 1);
      group_b := group_b || substring(alphabet
        from (1 + (get_byte(extensions.gen_random_bytes(1), 0) % 32))::int for 1);
      group_c := group_c || substring(alphabet
        from (1 + (get_byte(extensions.gen_random_bytes(1), 0) % 32))::int for 1);
      group_d := group_d || substring(alphabet
        from (1 + (get_byte(extensions.gen_random_bytes(1), 0) % 32))::int for 1);
    end loop;
    raw_code := group_a || '-' || group_b || '-' || group_c || '-' || group_d;
    -- Store the hash of the canonical (stripped) form so the consume
    -- function can match regardless of how the user pastes it back.
    canonical := regexp_replace(upper(raw_code), '[^A-Z0-9]', '', 'g');
    insert into public.mfa_recovery_codes (user_id, code_hash)
    values (uid, encode(extensions.digest(canonical, 'sha256'), 'hex'));
    -- Return the dashed form to the UI for readability.
    code := raw_code;
    return next;
  end loop;
  return;
end;
$$;

grant execute on function public.generate_mfa_recovery_codes() to authenticated;

create or replace function public.consume_mfa_recovery_code(p_code text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  uid uuid := auth.uid();
  canonical text;
  legacy text;
  hashed_canonical text;
  hashed_legacy text;
  matched_id uuid;
begin
  if uid is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;
  if p_code is null or length(trim(p_code)) = 0 then
    return false;
  end if;
  -- New canonical form: strip every non-alphanumeric char and uppercase.
  -- Tolerates pasted codes with or without dashes / inside whitespace.
  canonical := regexp_replace(upper(p_code), '[^A-Z0-9]', '', 'g');
  hashed_canonical := encode(extensions.digest(canonical, 'sha256'), 'hex');
  -- Legacy fallback for codes generated under 0027 before this migration.
  -- Original normalization kept the dashes inside the hashed input.
  legacy := upper(trim(p_code));
  hashed_legacy := encode(extensions.digest(legacy, 'sha256'), 'hex');

  update public.mfa_recovery_codes
    set used_at = now()
    where user_id = uid
      and used_at is null
      and (code_hash = hashed_canonical or code_hash = hashed_legacy)
    returning id into matched_id;
  return matched_id is not null;
end;
$$;

grant execute on function public.consume_mfa_recovery_code(text) to authenticated;
