-- Allow a CANCELLED purchase order's source file to be imported again, with
-- lineage back to the import it supersedes (owner request 2026-07-22).
--
-- Root cause of the bug this supports: PoImportsService dedupes uploads by
-- (organization_id, sha256) and blocks when a prior import's status is not in
-- (failed, canceled, duplicate). Cancelling the resulting PURCHASE ORDER never
-- touches the po_imports row, so the import stays 'approved' and that file is
-- permanently un-reimportable — even though the PO it produced is dead. Real
-- case: a PO approved against the wrong charter is cancelled, and the file can
-- never be re-imported to redo it.
--
-- NOTE: PO numbers are generated by next_po_number() at approve time and are
-- never taken from the imported document, so NO po_number uniqueness rule is
-- involved and none is changed here. This migration is purely ADDITIVE: one
-- nullable self-FK for lineage. No existing constraint is altered, no data is
-- rewritten, and nothing is deleted.

alter table public.po_imports
  add column if not exists reimported_from_id uuid
    references public.po_imports(id) on delete set null;

comment on column public.po_imports.reimported_from_id is
  'When this import re-uses a file whose previous import produced a CANCELLED '
  'purchase order, points at that predecessor import. Preserves lineage without '
  'mutating the predecessor (it and its cancelled PO stay intact for audit).';

-- Lineage lookups are "find the successor(s) of this import" — a small partial
-- index keeps that free without bloating the table's index set.
create index if not exists po_imports_reimported_from_idx
  on public.po_imports (reimported_from_id)
  where reimported_from_id is not null;

-- ROLLBACK (documented, reversible):
--   drop index if exists public.po_imports_reimported_from_idx;
--   alter table public.po_imports drop column if exists reimported_from_id;
